#!/usr/bin/env bun
// scripts/generate-help-content.ts — Generates src/help-content.ts from docs/*.md
//
// Usage:  bun run scripts/generate-help-content.ts
//
// Reads every *.md file in docs/ (excluding the agent/ subdirectory),
// extracts the title from the first "# Heading" line, and writes
// src/help-content.ts with the EMBEDDED_DOCS array and getEmbeddedDoc helper.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const DOCS_DIR = join(ROOT, "docs");
const OUTPUT = join(ROOT, "src", "help-content.ts");

/** Extract the title from the first `# Heading` line, or fall back to the filename. */
function extractTitle(content: string, filename: string): string {
  const match = content.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : filename.replace(/\.md$/, "");
}

/** Escape backticks and `${` sequences so the content is safe inside a template literal. */
function escapeForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function main() {
  // Collect only top-level .md files (skip agent/ subdirectory)
  const entries = await readdir(DOCS_DIR, { withFileTypes: true });
  const mdFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith(".md"))
    .map((e) => e.name)
    .sort();

  if (mdFiles.length === 0) {
    console.error("No .md files found in", DOCS_DIR);
    process.exit(1);
  }

  const docs: { filename: string; title: string; content: string }[] = [];

  for (const filename of mdFiles) {
    const raw = await readFile(join(DOCS_DIR, filename), "utf-8");
    const title = extractTitle(raw, filename);
    docs.push({ filename, title, content: raw });
  }

  // Build the output file
  const items = docs
    .map(
      (d) =>
        `  {\n    filename: "${d.filename}",\n    title: "${d.title}",\n    content: \`${escapeForTemplateLiteral(d.content.trimEnd())}\`,\n  }`,
    )
    .join(",\n");

  const output = `// src/help-content.ts — Embedded documentation content for the compiled binary
//
// AUTO-GENERATED by scripts/generate-help-content.ts — do not edit manually.
// When xTremeTerminal is compiled into a standalone binary (bun build --compile),
// external doc files in docs/ are not bundled. This module embeds the
// documentation content directly so the help system works in release builds.

export interface EmbeddedDoc {
  readonly filename: string;
  readonly title: string;
  readonly content: string;
}

export const EMBEDDED_DOCS: readonly EmbeddedDoc[] = [
${items},
];

/** Look up embedded doc content by filename */
export function getEmbeddedDoc(filename: string): string | null {
  const doc = EMBEDDED_DOCS.find((d) => d.filename === filename);
  return doc?.content ?? null;
}
`;

  await writeFile(OUTPUT, output, "utf-8");
  console.log(
    `Generated ${OUTPUT} with ${docs.length} docs: ${mdFiles.join(", ")}`,
  );
}

main();
