// src/help-content.ts — Embedded documentation content for the compiled binary
//
// AUTO-GENERATED by scripts/generate-help-content.ts — do not edit manually.
// When xTremeTerminal is compiled into a standalone binary (bun build --compile),
// external doc files in docs/ are not bundled. This module embeds the
// documentation content directly so the help system works in release builds.

export interface EmbeddedDoc {
  readonly filename: string;
  readonly title: string;
  readonly content: string;
}

export const EMBEDDED_DOCS: readonly EmbeddedDoc[] = [
  {
    filename: "architecture.md",
    title: "Architecture",
    content: `# Architecture

Technical architecture overview for xTremeTerminal, covering design decisions, component relationships, and data flow.

## Design Principles

### 1. Separation of Concerns

The codebase is organized into three layers:

\`\`\`
┌─────────────────────────┐
│      Components         │  TUI rendering + user interaction
│   (src/components/)     │  Depends on: OpenTUI, Services
├─────────────────────────┤
│       Services          │  Business logic + state management
│    (src/services/)      │  Depends on: nothing (pure logic)
├─────────────────────────┤
│       Utilities         │  Pure functions, mappings
│     (src/utils/)        │  Depends on: nothing
└─────────────────────────┘
\`\`\`

- **Services** have zero TUI dependency. They can be tested without a renderer.
- **Components** own their OpenTUI renderables and manage their lifecycle.
- **Utilities** are pure functions with no side effects.

### 2. App as Orchestrator

\`src/app.ts\` is the central coordinator. It:
- Creates the renderer
- Instantiates all components and services
- Wires them together via callbacks
- Routes keyboard events to the appropriate component
- Manages global state (which component is focused, etc.)

Components never communicate directly with each other. They communicate through the App.

### 3. State Flows Down, Events Flow Up

\`\`\`
     App (state owner)
      │         ▲
      │ state   │ events
      ▼         │
   Components ──┘
\`\`\`

The App passes state into components (e.g., "these are the open tabs"). Components emit events back to the App (e.g., "user clicked tab X"). The App processes the event, updates state, and pushes new state to affected components.

## Component Architecture

### Layout Hierarchy

\`\`\`
renderer.root
└── RootContainer (column)
    ├── TabBar (height: 1)
    ├── MiddleRow (row, flexGrow: 1)
    │   ├── Sidebar (width: 25)
    │   │   └── FileTree
    │   │       └── ScrollBox
    │   │           └── TreeItems...
    │   └── EditorArea (flexGrow: 1)
    │       └── ScrollBox
    │           └── LineNumbers + Textarea/Code
    └── StatusBar (height: 1)
\`\`\`

### Component Lifecycle

Each component follows a consistent pattern:

\`\`\`typescript
class SomeComponent {
  // 1. Construction: create renderables
  constructor(renderer: CliRenderer, options: Options) {
    this.container = new BoxRenderable(renderer, { ... })
    // ... create children
  }

  // 2. Rendering: update visual state
  render(state: SomeState): void {
    // Update renderable properties based on state
  }

  // 3. Event callbacks: communicate with App
  onSomeAction: (data: EventData) => void

  // 4. Cleanup: destroy renderables
  destroy(): void {
    this.container.destroy()
  }
}
\`\`\`

## Service Architecture

### FileService

Handles all file system I/O. Uses \`node:fs/promises\` for async operations.

\`\`\`
FileService
├── readDirectory(path) → FileEntry[]
├── readFileContent(path) → string
├── writeFileContent(path, content) → void
├── createFile(dir, name) → string
├── createDirectory(dir, name) → string
├── renameFile(old, new) → string
├── deleteFile(path) → void
├── deleteDirectory(path) → void
├── buildTree(root) → FileEntry[]
├── expandDirectory(entry) → FileEntry[]
├── isTextFile(path) → boolean
└── getFileStats(path) → FileStats
\`\`\`

### TabManager

Manages the state of all open tabs. Pure data management, no rendering.

\`\`\`
TabManager
├── tabs: TabState[]
├── activeTabId: string | null
├── openTab(path, content) → TabState
├── closeTab(id) → TabState | null
├── switchToTab(id) → TabState
├── nextTab() / previousTab() → TabState
├── updateTabContent(id, content) → void
├── updateTabCursor(id, line, col) → void
├── findTabByPath(path) → TabState | null
└── hasUnsavedTabs() → boolean
\`\`\`

### History

Per-tab undo/redo stack. Each tab gets its own History instance.

\`\`\`
History
├── undoStack: EditOperation[]
├── redoStack: EditOperation[]
├── push(operation) → void
├── undo() → EditOperation | null
├── redo() → EditOperation | null
├── merge(operation) → boolean
├── canUndo() / canRedo() → boolean
└── clear() → void
\`\`\`

### Clipboard

Simple internal buffer for copy/cut/paste operations.

\`\`\`
Clipboard
├── buffer: string
├── copy(text) → void
├── cut(text) → string
├── paste() → string
├── hasContent() → boolean
└── clear() → void
\`\`\`

## Data Flow Examples

### Opening a File from the File Tree

\`\`\`
1. User presses Enter on a file in FileTree
2. FileTree calls: onFileSelect(filePath)
3. App receives the event
4. App checks: TabManager.findTabByPath(filePath)
   - If tab exists: TabManager.switchToTab(id)
   - If not: FileService.readFileContent(filePath) → content
             TabManager.openTab(filePath, content) → tab
5. App updates: TabBar.render(tabs, activeId)
                Editor.loadFile(filePath, content)
                StatusBar.update(statusState)
\`\`\`

### Saving a File

\`\`\`
1. User presses Ctrl+S
2. App receives keypress (global handler)
3. App gets: Editor.content, Editor.currentFilePath
4. App calls: FileService.writeFileContent(path, content)
5. On success: TabManager.markModified(activeId, false)
               TabBar.render(tabs, activeId)
               StatusBar.showMessage("File saved", "success")
6. On error: StatusBar.showMessage("Error: ...", "error")
\`\`\`

### Undo Operation

\`\`\`
1. User presses Ctrl+Z
2. App receives keypress
3. App gets: activeTab.history.undo() → operation
4. If operation exists:
   - Apply reverse operation to editor content
   - Editor.setContent(newContent)
   - TabManager.updateTabContent(id, newContent)
\`\`\`

## Focus Management

xTremeTerminal has two focus zones:

1. **File Tree** - receives arrow keys for navigation, n/N/F2/Delete for file ops
2. **Editor** - receives all text input, editing shortcuts

Switching focus:
- **Tab** key or clicking switches focus between tree and editor
- When search dialog or command palette is open, they capture all input
- Overlays (confirm dialog, search) are modal -- they must be dismissed before returning to normal input

\`\`\`
Focus Priority (highest to lowest):
1. Confirm Dialog (modal)
2. Command Palette (modal)
3. Search Dialog (modal)
4. Editor (when focused)
5. File Tree (when focused)
\`\`\`

## Testing Architecture

### Three Test Layers

\`\`\`
┌───────────────────────────────────────────────────┐
│  Integration Tests (tests/integration/)            │
│  Full user workflows with simulated keyboard input │
│  Uses: headless renderer, temp directories         │
├───────────────────────────────────────────────────┤
│  Component Tests (tests/component/)                │
│  Individual components with a renderer             │
│  Uses: headless renderer (OTUI_NO_NATIVE_RENDER)   │
├───────────────────────────────────────────────────┤
│  Unit Tests (tests/unit/)                          │
│  Services and utilities in isolation               │
│  Uses: no renderer, mocked file system             │
└───────────────────────────────────────────────────┘
\`\`\`

### Test Helpers

- \`tests/helpers/setup.ts\` - Creates a headless renderer for component/integration tests, provides temp directory utilities
- \`tests/helpers/key-simulator.ts\` - Simulates keyboard input sequences by emitting KeyEvent objects through the renderer's keyInput handler

### Headless Renderer for Tests

\`\`\`typescript
const renderer = await createCliRenderer({
  exitOnCtrlC: false,
  useAlternateScreen: false,
})
// Set OTUI_NO_NATIVE_RENDER=true in environment
\`\`\`

This allows tests to create renderables and simulate input without needing an actual terminal.

## Technology Choices

### Why OpenTUI?

- **Same library as OpenCode** - proven at scale in a real product
- **Built-in Tree-sitter** - syntax highlighting without additional dependencies
- **Yoga layout engine** - CSS Flexbox in the terminal, responsive layouts
- **Imperative API** - direct control over renderables, good for stateful components
- **Rich component library** - Text, Box, Input, Textarea, ScrollBox, Code, etc.

### Why Bun?

- **Required by OpenTUI** - OpenTUI uses Bun-specific FFI for native rendering
- **Fast startup** - important for a CLI tool
- **Built-in test runner** - no need for Jest/Vitest
- **TypeScript-first** - runs .ts files directly without compilation

### Why Imperative API (not SolidJS/React)?

- **Direct control** - easier to manage complex stateful interactions (editor, tree)
- **Less overhead** - no reactive framework runtime
- **Predictable rendering** - explicit render calls, no virtual DOM diffing
- **Simpler testing** - components are regular classes with methods

## File Format Support

xTremeTerminal edits plain text files. It intentionally does not support:
- Binary file editing (hex editors are better for this)
- Rich text / WYSIWYG editing
- Image viewing (beyond file tree icons)

Detection of "editable" files:
1. Check file extension against known binary list
2. Read first 8KB and check for null bytes
3. If null bytes found → binary → show warning
4. Otherwise → text → open for editing`,
  },
  {
    filename: "configuration.md",
    title: "Configuration",
    content: `# Configuration

xTremeTerminal uses a Tokyo Night inspired dark theme by default. This document describes the theme configuration and customization options.

## Theme

### Color Palette

xTremeTerminal uses the following color palette, inspired by the [Tokyo Night](https://github.com/enkia/tokyo-night-vscode-theme) VS Code theme:

#### Background Colors

| Constant | Hex | Usage |
|----------|-----|-------|
| \`BG_PRIMARY\` | \`#1a1b26\` | Editor background |
| \`BG_SECONDARY\` | \`#16161e\` | Sidebar, tab bar, status bar |
| \`BG_HIGHLIGHT\` | \`#24283b\` | Current line, hover state, selected tree item |
| \`BG_SELECTION\` | \`#283457\` | Text selection in editor |

#### Foreground Colors

| Constant | Hex | Usage |
|----------|-----|-------|
| \`FG_PRIMARY\` | \`#a9b1d6\` | Default text, file names |
| \`FG_SECONDARY\` | \`#565f89\` | Comments, disabled items, inactive tabs |
| \`FG_MUTED\` | \`#3b4261\` | Line numbers, borders, separators |

#### Accent Colors

| Constant | Hex | Usage |
|----------|-----|-------|
| \`ACCENT\` | \`#7aa2f7\` | Active tab, focused elements, cursor, links |
| \`ERROR\` | \`#f7768e\` | Error messages, delete indicators |
| \`WARNING\` | \`#e0af68\` | Warning messages, modified indicators |
| \`SUCCESS\` | \`#9ece6a\` | Success messages, strings in syntax |
| \`INFO\` | \`#7dcfff\` | Info messages, types in syntax |

### Syntax Highlighting Colors

The syntax highlighting theme follows Tokyo Night conventions:

| Token Type | Color | Example |
|-----------|-------|---------|
| Keywords | \`#bb9af7\` (purple) | \`const\`, \`function\`, \`return\`, \`if\` |
| Strings | \`#9ece6a\` (green) | \`"hello world"\` |
| Comments | \`#565f89\` (gray, italic) | \`// this is a comment\` |
| Numbers | \`#ff9e64\` (orange) | \`42\`, \`3.14\`, \`true\` |
| Functions | \`#7aa2f7\` (blue) | \`console.log()\`, \`fetch()\` |
| Types | \`#2ac3de\` (cyan) | \`string\`, \`number\`, \`interface\` |
| Variables | \`#c0caf5\` (light blue) | \`myVariable\`, \`data\` |
| Properties | \`#7dcfff\` (sky blue) | \`.length\`, \`.name\` |
| Operators | \`#89ddff\` (light cyan) | \`=\`, \`+\`, \`=>\`, \`&&\` |
| Tags (HTML) | \`#f7768e\` (red) | \`<div>\`, \`<span>\` |
| Attributes | \`#bb9af7\` (purple) | \`class=\`, \`id=\` |

### UI Element Styling

| Element | Background | Foreground | Notes |
|---------|-----------|------------|-------|
| Editor | \`BG_PRIMARY\` | \`FG_PRIMARY\` | Main editing area |
| Sidebar | \`BG_SECONDARY\` | \`FG_PRIMARY\` | File tree container |
| Tab bar | \`BG_SECONDARY\` | \`FG_SECONDARY\` | Inactive tab area |
| Active tab | \`BG_PRIMARY\` | \`ACCENT\` | Currently selected tab |
| Inactive tab | \`BG_SECONDARY\` | \`FG_SECONDARY\` | Other tabs |
| Modified tab | \`BG_SECONDARY\` | \`WARNING\` | Dot indicator |
| Status bar | \`BG_SECONDARY\` | \`FG_PRIMARY\` | Bottom status |
| Line numbers | \`BG_SECONDARY\` | \`FG_MUTED\` | Gutter |
| Current line | \`BG_HIGHLIGHT\` | - | Highlighted line |
| Selection | \`BG_SELECTION\` | - | Selected text |
| Search match | \`#e0af68\` bg | - | Highlighted matches |
| Active match | \`#ff9e64\` bg | - | Current match |
| Scrollbar track | \`BG_SECONDARY\` | - | Scrollbar background |
| Scrollbar thumb | \`FG_MUTED\` | - | Scrollbar indicator |
| Dialog overlay | \`BG_HIGHLIGHT\` | \`FG_PRIMARY\` | Confirm/search dialogs |
| Command palette | \`BG_HIGHLIGHT\` | \`FG_PRIMARY\` | Command list |

## Editor Settings

### Indentation

Default: 4 spaces. The editor uses soft tabs (spaces) by default.

### Word Wrap

Default: Off (no wrap). Code is displayed without line wrapping. Use horizontal scrolling for long lines.

### Encoding

Default: UTF-8. xTremeTerminal reads and writes files in UTF-8 encoding.

## File Handling

### File Size Limits

| Size | Behavior |
|------|----------|
| < 1 MB | Opens normally |
| 1 MB - 10 MB | Warning shown before opening |
| > 10 MB | Refused (too large for terminal editing) |

### Binary Files

Binary files (detected by null bytes in the first 8KB) are not opened for editing. xTremeTerminal displays a message: "Binary file - cannot edit".

Known binary extensions that skip content detection:
\`.png\`, \`.jpg\`, \`.jpeg\`, \`.gif\`, \`.bmp\`, \`.ico\`, \`.svg\`, \`.mp3\`, \`.mp4\`, \`.avi\`,
\`.zip\`, \`.tar\`, \`.gz\`, \`.7z\`, \`.rar\`, \`.exe\`, \`.dll\`, \`.so\`, \`.dylib\`, \`.o\`,
\`.pdf\`, \`.doc\`, \`.docx\`, \`.xls\`, \`.xlsx\`, \`.ppt\`, \`.pptx\`

### Auto-Detection

| Feature | Method |
|---------|--------|
| Language | File extension mapping (see \`src/utils/language-detect.ts\`) |
| Encoding | Always UTF-8 |
| Line endings | Detected from file content |

## Terminal Requirements

| Feature | Minimum | Recommended |
|---------|---------|-------------|
| Terminal size | 40 x 10 | 120 x 40 or larger |
| Color support | 256 colors | True color (24-bit) |
| Alternate screen | Required | Required |
| Mouse support | Optional | Recommended |
| Unicode | Basic | Full (for file icons) |

## Environment Variables

xTremeTerminal inherits OpenTUI's environment variable support:

| Variable | Description |
|----------|-------------|
| \`OTUI_NO_NATIVE_RENDER\` | Disable native rendering (for testing) |
| \`OTUI_USE_ALTERNATE_SCREEN\` | Override alternate screen setting |
| \`OTUI_SHOW_STATS\` | Show debug overlay |`,
  },
  {
    filename: "getting-started.md",
    title: "Getting Started",
    content: `# Getting Started

This guide walks you through installing and running xTremeTerminal for the first time.

## Prerequisites

Before installing xTremeTerminal, make sure you have the following:

### 1. Bun (required)

xTremeTerminal runs on [Bun](https://bun.sh), a fast JavaScript/TypeScript runtime. Node.js will not work because xTremeTerminal's underlying UI library (OpenTUI) uses Bun-specific FFI bindings.

\`\`\`bash
# Install Bun
curl -fsSL https://bun.sh/install | bash

# Verify installation
bun --version   # Should be >= 1.0
\`\`\`

### 2. Zig (required for building)

[Zig](https://ziglang.org) is needed to compile OpenTUI's native terminal rendering library. You need it at install time; it is not required at runtime once dependencies are installed.

\`\`\`bash
# Option A: Download and install manually
curl -fsSL https://ziglang.org/download/0.14.1/zig-linux-x86_64-0.14.1.tar.xz | tar -xJ
sudo mv zig-linux-x86_64-0.14.1 /opt/zig
sudo ln -s /opt/zig/zig /usr/local/bin/zig

# Option B: Install via package manager (Ubuntu/Debian)
sudo snap install zig --classic

# Verify installation
zig version   # Should be >= 0.13
\`\`\`

### 3. Terminal

xTremeTerminal works best with a modern terminal emulator that supports:
- **True color** (24-bit color) - for the full Tokyo Night theme
- **256 colors** minimum - basic theme support
- **Alternate screen buffer** - xTremeTerminal takes over the full terminal
- **Mouse input** (optional) - for clicking tabs and tree items

Recommended terminals: Kitty, Alacritty, WezTerm, iTerm2, Windows Terminal, GNOME Terminal.

## Installation

### From Source

\`\`\`bash
# Clone the repository
git clone https://github.com/your-username/xTremeTerminal.git
cd xTremeTerminal

# Install dependencies
bun install

# Run xTremeTerminal
bun run src/index.ts
\`\`\`

### Global Install

\`\`\`bash
# Install as a global CLI tool
cd xTremeTerminal
bun install -g .

# Now you can run from anywhere
xterm
\`\`\`

## First Run

### Opening in the Current Directory

\`\`\`bash
bun run src/index.ts
\`\`\`

This opens xTremeTerminal with the file tree showing the current working directory.

### Opening a Specific Directory

\`\`\`bash
bun run src/index.ts /path/to/project
\`\`\`

### Opening a Specific File

\`\`\`bash
bun run src/index.ts /path/to/file.ts
\`\`\`

## Your First Session

When xTremeTerminal launches, you'll see:

\`\`\`
┌─────────────────────────────────────────────────────────────┐
│  [Welcome]                                                   │
├──────────────┬──────────────────────────────────────────────┤
│              │                                               │
│  File Tree   │  Editor Area                                  │
│              │                                               │
│  > src/      │  Welcome to xTremeTerminal!                            │
│  > tests/    │                                               │
│    README.md │  Use arrow keys to navigate the file tree.    │
│    ...       │  Press Enter to open a file.                  │
│              │                                               │
├──────────────┴──────────────────────────────────────────────┤
│  Welcome | Ln 1, Col 1 | Ready                               │
└─────────────────────────────────────────────────────────────┘
\`\`\`

### Basic Workflow

1. **Navigate the file tree** using the **Up** and **Down** arrow keys
2. **Expand a directory** by pressing **Enter** or **Right arrow**
3. **Open a file** by selecting it and pressing **Enter**
4. **Edit the file** -- just start typing
5. **Save your changes** with **Ctrl+S**
6. **Open another file** -- it opens in a new tab
7. **Switch between tabs** with **Ctrl+Tab**
8. **Exit** with **Ctrl+C**

### Key Things to Know

- The **file tree** is on the left; the **editor** is on the right
- **Tabs** appear at the top when you have multiple files open
- The **status bar** at the bottom shows the current file, cursor position, and language
- A **dot** before a tab name means the file has unsaved changes
- Press **Ctrl+B** to toggle the sidebar if you need more editor space
- Press **Ctrl+Shift+P** to open the command palette for all available actions

## Next Steps

- Read the [User Guide](user-guide.md) for detailed usage instructions
- Check the [Keyboard Shortcuts](keyboard-shortcuts.md) reference
- Learn about [Configuration](configuration.md) options
- Explore the [Architecture](architecture.md) for technical details

## Troubleshooting

### "command not found: bun"
Make sure Bun is installed and in your PATH. Run \`source ~/.bashrc\` after installing.

### "error: zig not found"
OpenTUI requires Zig to build its native components. Install Zig and make sure it's in your PATH.

### Colors look wrong
Your terminal may not support true color. Try setting \`COLORTERM=truecolor\` in your environment, or switch to a terminal that supports 24-bit color.

### Terminal looks garbled after crash
If xTremeTerminal exits abnormally without cleaning up the terminal, run:
\`\`\`bash
reset
\`\`\`
This restores your terminal to its normal state.

### "Terminal too small"
xTremeTerminal requires a minimum of 40 columns and 10 rows. Resize your terminal window.`,
  },
  {
    filename: "keyboard-shortcuts.md",
    title: "Keyboard Shortcuts",
    content: `# Keyboard Shortcuts

Complete reference of all keyboard shortcuts in xTremeTerminal.

---

## Global Shortcuts

These work regardless of which component is focused.

| Shortcut | Action |
|----------|--------|
| Ctrl+Q | Exit xTremeTerminal (with unsaved changes confirmation) |
| Ctrl+B | Toggle sidebar visibility |
| Ctrl+Shift+P | Open command palette |
| F10 | Open menu bar |
| Ctrl+E | Focus file tree |
| Ctrl+G | Focus editor |

---

## File Operations

| Shortcut | Action |
|----------|--------|
| Ctrl+S | Save current file |
| Ctrl+N | New untitled file (opens in new tab) |

---

## Tab Management

| Shortcut | Action |
|----------|--------|
| Alt+Right | Switch to next tab |
| Alt+Left | Switch to previous tab |
| Ctrl+W | Close current tab |

---

## Editor - Cursor Movement

| Shortcut | Action |
|----------|--------|
| Up / Down / Left / Right | Move cursor by one character or line |
| Home | Move to beginning of current line |
| End | Move to end of current line |
| Page Up | Move up one page |
| Page Down | Move down one page |
| Ctrl+Left | Move to previous word boundary |
| Ctrl+Right | Move to next word boundary |
| Ctrl+Home | Move to beginning of file |
| Ctrl+End | Move to end of file |

---

## Editor - Text Selection

| Shortcut | Action |
|----------|--------|
| Shift+Up | Select line above |
| Shift+Down | Select line below |
| Shift+Left | Extend selection left by one character |
| Shift+Right | Extend selection right by one character |
| Shift+Home | Select to beginning of line |
| Shift+End | Select to end of line |
| Ctrl+Shift+Left | Select to previous word boundary |
| Ctrl+Shift+Right | Select to next word boundary |
| Ctrl+A | Select all text |

---

## Editor - Editing

| Shortcut | Action |
|----------|--------|
| Backspace | Delete character before cursor |
| Delete | Delete character after cursor |
| Enter | Insert new line |
| Tab | Insert indentation (spaces or tab character) |
| Ctrl+Z | Undo last change |
| Ctrl+Y | Redo last undone change |
| Ctrl+Shift+Z | Redo (alternative) |

---

## Editor - Clipboard

| Shortcut | Action |
|----------|--------|
| Ctrl+C | Copy selected text (when text is selected) |
| Ctrl+X | Cut selected text |
| Ctrl+V | Paste from clipboard |

Note: Ctrl+C only copies when text is selected; it does not exit the application.

---

## Search and Replace

| Shortcut | Action |
|----------|--------|
| Ctrl+F | Open find dialog |
| Ctrl+Shift+H | Open find and replace dialog |
| Enter | Next match (when find dialog is focused) |
| Shift+Enter | Previous match (when find dialog is focused) |
| Escape | Close search dialog |

---

## Menu Bar

| Shortcut | Action |
|----------|--------|
| F10 | Open/close menu bar |
| Left / Right | Navigate between menus |
| Down / Enter | Open dropdown for selected menu |
| Up / Down | Navigate dropdown items |
| Enter | Execute selected menu item |
| Escape | Close menu bar |

---

## Archive Browser

These shortcuts work when an archive file is open in the archive browser.

| Shortcut | Action |
|----------|--------|
| Up / Down | Move selection up / down |
| Enter | View selected file (opens in a new tab as read-only) |
| e | Extract selected entry to a chosen directory |
| Ctrl+E | Extract entire archive to a chosen directory |
| Left / Right | Reserved (no-op, for future expand/collapse) |

---

## File Tree

These shortcuts work when the file tree is focused.

| Shortcut | Action |
|----------|--------|
| Up / Down | Move selection up / down |
| Enter | Expand directory or open file |
| Right | Expand directory |
| Left | Collapse directory or move to parent |
| Home | Jump to first item |
| End | Jump to last item |
| Page Up / Down | Scroll by page |
| n | Create new file in selected directory |
| N (Shift+n) | Create new directory in selected directory |
| F2 | Rename selected item |
| Delete | Delete selected item (with confirmation) |

---

## Command Palette

These shortcuts work when the command palette is open.

| Shortcut | Action |
|----------|--------|
| Up / Down | Navigate command list |
| Enter | Execute selected command |
| Escape | Close command palette |
| Type text | Filter commands by name |

---

## File Search / Filter

| Shortcut | Action |
|----------|--------|
| Ctrl+P | Open file search/filter |
| Up / Down | Navigate filtered results |
| Enter | Open selected file |
| Escape | Close filter |

---

## Quick Reference Card

\`\`\`
╔═══════════════════════════════════════════════════════╗
║                    xTremeTerminal Shortcuts                     ║
╠═══════════════════════════════════════════════════════╣
║  FILES           TABS            EDITING              ║
║  Ctrl+S  Save    Alt+Right Next  Ctrl+Z  Undo        ║
║  Ctrl+N  New     Alt+Left  Prev  Ctrl+Y  Redo        ║
║  Ctrl+Q  Quit    Ctrl+W   Close  Ctrl+C  Copy        ║
║                                  Ctrl+X  Cut         ║
║  SEARCH          VIEW            Ctrl+V  Paste       ║
║  Ctrl+F  Find    Ctrl+B  Sidebar Ctrl+A  Select All  ║
║  Ctrl+Shift+H    Ctrl+E  Tree                        ║
║    Replace       Ctrl+G  Editor                      ║
║                  Ctrl+Shift+P  Command Palette       ║
║                  F10     Menu                         ║
║  TREE                                                 ║
║  n       New file    F2     Rename                    ║
║  N       New dir     Del    Delete                    ║
║  Enter   Open/Expand Left   Collapse                  ║
╚═══════════════════════════════════════════════════════╝
\`\`\``,
  },
  {
    filename: "user-guide.md",
    title: "User Guide",
    content: `# User Guide

This is the complete usage manual for xTremeTerminal, covering all features from file browsing to advanced text editing.

## Table of Contents

- [Interface Overview](#interface-overview)
- [File Tree Browser](#file-tree-browser)
- [Text Editor](#text-editor)
- [Tabs](#tabs)
- [Archive Browser](#archive-browser)
- [Search and Replace](#search-and-replace)
- [File Operations](#file-operations)
- [Menu Bar](#menu-bar)
- [Command Palette](#command-palette)
- [Help System](#help-system)
- [Status Bar](#status-bar)

---

## Interface Overview

xTremeTerminal uses a VS Code-style layout with five main areas:

\`\`\`
┌─────────────────────────────────────────────────────────┐
│  Menu Bar                                                │
├─────────────────────────────────────────────────────────┤
│  Tab Bar                                                 │
├──────────────┬──────────────────────────────────────────┤
│              │                                           │
│  File Tree   │  Editor                                   │
│  (Sidebar)   │                                           │
│              │                                           │
├──────────────┴──────────────────────────────────────────┤
│  Status Bar                                              │
└─────────────────────────────────────────────────────────┘
\`\`\`

### Menu Bar
A top-level menu bar with **File** and **Help** menus. Open it with **F10** and navigate with arrow keys.

### Tab Bar
Shows all currently open files. The active tab is highlighted with an accent color. Tabs with unsaved changes show a dot indicator.

### File Tree (Sidebar)
An expandable/collapsible directory tree on the left side. Toggle visibility with **Ctrl+B**.

### Editor
The main text editing area with line numbers, syntax highlighting, and cursor.

### Status Bar
Shows current file info: filename, cursor position, language, encoding, and modification state. Also displays temporary messages for operations like save or errors.

---

## File Tree Browser

The file tree shows the directory structure starting from the directory where xTremeTerminal was launched (or the path provided as a CLI argument).

### Navigation

| Key | Action |
|-----|--------|
| Up / Down | Move selection up / down |
| Enter / Right | Expand directory or open file |
| Left | Collapse directory or move to parent |
| Home | Jump to first item |
| End | Jump to last item |
| Page Up / Down | Scroll by page |

### Visual Indicators

- \`▶\` Collapsed directory
- \`▼\` Expanded directory
- Icons are shown based on file type (e.g., TypeScript, JavaScript, JSON, Markdown)
- The selected item is highlighted with a distinct background color

### File Filtering

Press **Ctrl+P** to activate file search/filter mode. Type a filename pattern to filter the tree and quickly jump to a file.

### Directory Loading

Directories are loaded lazily -- children are only read from disk when you expand a directory. This keeps the tree responsive even in large projects.

---

## Text Editor

### Basic Editing

xTremeTerminal provides a full text editor with all standard editing operations:

- **Type** to insert text at the cursor position
- **Backspace** deletes the character before the cursor
- **Delete** deletes the character after the cursor
- **Enter** inserts a new line

### Cursor Movement

| Key | Action |
|-----|--------|
| Arrow keys | Move cursor one character/line |
| Home | Move to beginning of line |
| End | Move to end of line |
| Page Up | Move up one page |
| Page Down | Move down one page |
| Ctrl+Left | Move to previous word |
| Ctrl+Right | Move to next word |

### Text Selection

Hold **Shift** while pressing movement keys to select text:

| Key | Action |
|-----|--------|
| Shift+Arrow | Select character by character |
| Shift+Home | Select to line start |
| Shift+End | Select to line end |
| Ctrl+A | Select all text |

### Clipboard

| Key | Action |
|-----|--------|
| Ctrl+C | Copy selected text |
| Ctrl+X | Cut selected text |
| Ctrl+V | Paste clipboard content |

Note: xTremeTerminal uses an internal clipboard buffer. System clipboard integration may be available depending on your terminal's OSC 52 support. Ctrl+C only copies when text is selected; it does not exit the application.

### Undo / Redo

| Key | Action |
|-----|--------|
| Ctrl+Z | Undo last change |
| Ctrl+Y | Redo last undone change |

Undo history is maintained per-tab. Consecutive character typing is merged into single undo operations so you don't have to undo character by character.

### Saving Files

| Key | Action |
|-----|--------|
| Ctrl+S | Save the current file |

The status bar shows a confirmation message when the file is saved, and the modified indicator on the tab disappears.

### Syntax Highlighting

xTremeTerminal automatically detects the programming language based on the file extension and applies syntax highlighting using Tree-sitter. Supported languages include:

- TypeScript / JavaScript / JSX / TSX
- Python
- Rust
- Go
- Zig
- HTML / CSS
- JSON / YAML / TOML
- Markdown
- Bash / Shell
- And more

The detected language is shown in the status bar.

### Line Numbers

Line numbers are displayed in a gutter on the left side of the editor. The current line is highlighted.

---

## Tabs

xTremeTerminal supports multiple open files using a tabbed interface.

### Opening Tabs

- **Select a file** in the file tree and press **Enter** -- it opens in a new tab
- If the file is already open, xTremeTerminal switches to the existing tab instead of opening a duplicate

### Switching Tabs

| Key | Action |
|-----|--------|
| Alt+Right | Switch to the next tab |
| Alt+Left | Switch to the previous tab |

### Closing Tabs

| Key | Action |
|-----|--------|
| Ctrl+W | Close the current tab |

If the file has unsaved changes, xTremeTerminal will ask for confirmation before closing:

\`\`\`
Save changes to filename.ts? [Y/n/Cancel]
\`\`\`

- **Y** or **Enter**: Save and close
- **n**: Discard changes and close
- **Cancel** or **Escape**: Cancel, keep the tab open

### Tab Indicators

- Active tab: highlighted background with accent color
- Modified tab: shows a **dot** before the filename
- Each tab independently tracks: cursor position, scroll position, undo history

### Creating New Files

| Key | Action |
|-----|--------|
| Ctrl+N | Create a new untitled tab |

---

## Archive Browser

xTremeTerminal can browse the contents of archive files (\`.tar\`, \`.tar.gz\`, \`.tgz\`) directly without extracting them first.

### Opening Archives

Select an archive file in the file tree and press **Enter**. Instead of opening in the text editor, a dedicated archive browser opens in a new tab showing the archive's contents.

### Navigation

| Key | Action |
|-----|--------|
| Up / Down | Move selection up / down through archive entries |
| Enter | View selected file (opens content in a new tab) |
| e | Extract the selected entry to a chosen directory |
| Ctrl+E | Extract the entire archive to a chosen directory |

### Viewing Files

Press **Enter** on a file entry to view its content. The file opens in a new untitled tab with the content read directly from the archive. Directory entries are displayed but cannot be "opened".

### Extracting Files

- Press **e** on any entry to extract it. A path picker dialog appears where you can choose the destination directory.
- Press **Ctrl+E** to extract the entire archive. The same path picker dialog lets you choose where to extract all files.

After extraction, the file tree refreshes to show the newly extracted files.

### Path Picker

When extracting, a directory picker dialog appears:

\`\`\`
┌───────────────────────────────────────────────┐
│ Extract to...                                  │
│ /home/user/projects/myproject                  │
│ > ..                                           │
│   src/                                         │
│   docs/                                        │
│   tests/                                       │
│ [Select Here]  [Cancel]                        │
└───────────────────────────────────────────────┘
\`\`\`

- Use **Up / Down** to navigate directories
- Press **Enter** to descend into a directory
- Press **Tab** to switch between the list and buttons
- Select "Select Here" to extract to the current directory
- Press **Escape** or select "Cancel" to abort

### Supported Formats

| Format | Extensions |
|--------|-----------|
| tar | \`.tar\` |
| gzip-compressed tar | \`.tar.gz\`, \`.tgz\` |

### Status Bar

When viewing an archive, the status bar shows the archive filename, and the language is displayed as "Archive".

---

## Search and Replace

### Find

Press **Ctrl+F** to open the search dialog:

\`\`\`
┌─────────────────────────────────────┐
│ Find:    [search term          ] ↑↓ │
│ 3 of 12 matches                     │
└─────────────────────────────────────┘
\`\`\`

- Type your search term -- matches are highlighted in real-time
- Press **Enter** or the down arrow to jump to the next match
- Press **Shift+Enter** or the up arrow to jump to the previous match
- Press **Escape** to close the search dialog

### Find and Replace

Press **Ctrl+Shift+H** to open the find and replace dialog:

\`\`\`
┌─────────────────────────────────────┐
│ Find:    [search term          ] ↑↓ │
│ Replace: [replacement          ]    │
│ [Replace] [Replace All] [Close]     │
│ 3 of 12 matches                     │
└─────────────────────────────────────┘
\`\`\`

- **Replace**: Replace the current match and move to the next
- **Replace All**: Replace all matches at once
- Match count updates as you type

---

## File Operations

### From the File Tree

| Key | Action |
|-----|--------|
| n | Create a new file in the selected directory |
| N (Shift+n) | Create a new directory |
| F2 | Rename the selected file or directory |
| Delete | Delete the selected file or directory |

### Create New File/Directory

1. Select a directory in the file tree (or a file -- its parent directory will be used)
2. Press **n** for a new file or **N** for a new directory
3. Type the name and press **Enter**
4. The new item appears in the tree and (for files) opens in a new tab

### Rename

1. Select the file or directory in the file tree
2. Press **F2**
3. Edit the name and press **Enter**
4. If the file is open in a tab, the tab title updates automatically

### Delete

1. Select the file or directory in the file tree
2. Press **Delete**
3. A confirmation dialog appears: "Delete {name}? This action cannot be undone."
4. Press **Y** to confirm or **N** / **Escape** to cancel
5. If the file was open in a tab, the tab is closed

---

## Menu Bar

Press **F10** to open the menu bar at the top of the screen.

### File Menu

| Item | Shortcut | Action |
|------|----------|--------|
| Open File | Ctrl+E | Focus the file tree |
| Save File | Ctrl+S | Save the current file |
| Exit | Ctrl+Q | Exit xTremeTerminal |

### Help Menu

| Item | Action |
|------|--------|
| Search Docs | Search through documentation files |
| Help Topics | Browse help topics |
| About | Show About dialog |

### Navigation

- Use **Left / Right** arrows to switch between menus
- Press **Enter** or **Down** to open a dropdown
- Use **Up / Down** arrows to navigate dropdown items
- Press **Enter** to execute an item
- Press **Escape** to close

---

## Command Palette

Press **Ctrl+Shift+P** to open the command palette:

\`\`\`
┌────────────────────────────────────────┐
│ > search commands...                    │
├────────────────────────────────────────┤
│   Save File                  Ctrl+S    │
│   New File                   Ctrl+N    │
│   Close Tab                  Ctrl+W    │
│   Find                       Ctrl+F    │
│   Toggle Sidebar             Ctrl+B    │
│   ...                                  │
└────────────────────────────────────────┘
\`\`\`

- Type to filter commands by name
- Use **Up / Down** arrows to navigate
- Press **Enter** to execute the selected command
- Press **Escape** to close without executing

---

## Help System

xTremeTerminal includes a built-in help system accessible from the **Help** menu (F10, then navigate to Help).

### Help Topics

Browse through available documentation topics:

- **Keyboard Shortcuts** — Complete shortcut reference
- **Getting Started** — Quick start guide
- **User Guide** — This document
- **Configuration** — Configuration options
- **Architecture** — Technical design

Navigate with **Up / Down** arrows and press **Enter** to view a topic. Press **Escape** to go back to the topic list.

### Search Documentation

Search through all documentation files for specific keywords. Type your query and matching lines from all help files are shown with their source file and line number.

### About Dialog

Shows application information: version, author, license, and project link.

---

## Status Bar

The status bar at the bottom shows:

\`\`\`
 index.ts | Ln 3, Col 12 | TypeScript | UTF-8 | 4 spaces | Modified
\`\`\`

| Section | Description |
|---------|-------------|
| Filename | Name of the current file (or "Untitled") |
| Ln, Col | Current cursor position (line and column) |
| Language | Detected programming language |
| Encoding | File encoding (UTF-8) |
| Indent | Indentation style (spaces or tabs) |
| Modified | Shows when the file has unsaved changes |

### Temporary Messages

The status bar also displays temporary messages:
- "File saved" after Ctrl+S
- Error messages for failed operations (e.g., "Error: Permission denied")
- These messages appear briefly then return to the normal display

---

## Exiting

Press **Ctrl+Q** to exit xTremeTerminal. If you have unsaved changes, a confirmation dialog will appear:

\`\`\`
Unsaved Changes — 3 file(s) have unsaved changes. Exit?
[Exit] [Cancel]
\`\`\`

- **Exit**: Exit immediately (changes are lost)
- **Cancel** or **Escape**: Cancel and return to the editor

---

## Tips and Tricks

1. **Toggle the sidebar** with Ctrl+B to get more editor space when you don't need the file tree
2. **Use the command palette** (Ctrl+Shift+P) when you forget a shortcut
3. **Use the menu bar** (F10) for quick access to file operations and help
4. **Ctrl+P** quickly filters the file tree to find files by name
5. **Ctrl+E** focuses the file tree, **Ctrl+G** focuses the editor -- quick panel switching
6. **Tabs preserve state** -- your cursor position and scroll are remembered per tab
7. **Search documentation** from the Help menu to find answers without leaving the editor`,
  },
];

/** Look up embedded doc content by filename */
export function getEmbeddedDoc(filename: string): string | null {
  const doc = EMBEDDED_DOCS.find((d) => d.filename === filename);
  return doc?.content ?? null;
}
